### ISSUE TITLE
Support empty sourceType

### ISSUE THREAD

**Issue by Allsimon** [rodnansol/spring-configuration-property-documenter#33]
**Describe the bug**
If the sourceType is omitted, the generator will throw a NullPointer: 
```
Caused by: java.lang.NullPointerException: element cannot be mapped to a null key
...
	at org.rodnansol.core.generator.reader.MetadataReader.getPropertyMap(MetadataReader.java:134)
	at org.rodnansol.core.generator.reader.MetadataReader.readPropertiesAsPropertyGroupList(MetadataReader.java:67)
	... 17 common frames omitted
```

From the Spring Documentation, the sourceType attribute is not required:
https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#appendix.configuration-metadata.format.group
> If the source type is not known, the attribute may be omitted

**To Reproduce**

I think this will reproduce with manually written `spring-configuration-metadata.json` like:
```json
{
  "groups": [],
  "properties": [
    {
      "name": "myproduct.features.foobar.enabled",
      "type": "java.lang.Boolean",
      "description": "Enable the foobar feature",
      "defaultValue": true
    }
  ],
  "hints": []
}
```

**Comment by nandorholozsnyak** [comment]
Hello @Allsimon ,

Thank you for the issue ticket, let me take a look on it.

**Comment by nandorholozsnyak** [comment]
I see the problem, but I'm curious how this can happen, @Allsimon do you have a project reproducer for it or just example source codes as comment?

**Comment by nandorholozsnyak** [comment]
Hello @Allsimon 
Fix should be available in the new release: https://github.com/rodnansol/spring-configuration-property-documenter/releases/tag/v0.3.0

**Comment by Allsimon** [comment]
Wow that was fast 👍 
We manually write our spring-configuration-metadata.json when the properties is used only once where @ConfigurationProperties can't be injected (mostly annotations)

0.3.0 works fine, thanks a lot !

**Comment by nandorholozsnyak** [comment]
You are welcome @Allsimon, let us know if there are any other issues.

A few questions if you don't mind:
- Where did you find the project?
- Have you documented the configuration properties before, if yes how and where?
- If the JSON file is written manually and where do you store it?
- Do you mean to use configuration properties inside other annotations?
- Which output format do you use or prefer (Markdown, AsciiDoc, Html, XML)?

Have a nice day.

**Comment by Allsimon** [comment]
- Where did you find the project?
I checked the issues on Spring Boot project and find out via your comment: https://github.com/spring-projects/spring-boot/issues/33555

- Have you documented the configuration properties before, if yes how and where?
I made a custom generator based on the `/actuator/configprops` but a lot of things were missing, your plugin seems way more complete

- If the JSON file is written manually and where do you store it?
In the git repo, checked in with rest of the code

- Do you mean to use configuration properties inside other annotations?
Sorry that was confusing, for annotation like `@KafkaListener(topics = "${foobar.topics}")` I prefer to directly write the `spring-configuration-metadata.json` instead of having something like:
```java
@ConfigurationProperties(prefix = "foobar")
public record FoobarConfig(String topics) {}
``` 
that looks like dead code since it's not detected as used anywhere by the IDE
   
- Which output format do you use or prefer (Markdown, AsciiDoc, Html, XML)?
I'm using AsciiDoc for $CURRENT_JOB and will probably also use Markdown
