### ISSUE TITLE
Add the ENV_VARIABLE form

### ISSUE THREAD

**Issue by Allsimon** [rodnansol/spring-configuration-property-documenter#36]
I use environment variable to configure my application but the conversion "properties -> env variable" is not always trivial.

It would be very useful to have a copy-pastable ENV_VARIABLE form.

**Describe the solution you'd like**

For example, the Markdown generator currently outputs:

---
### spring.kafka
**Class:** `org.springframework.boot.autoconfigure.kafka.KafkaProperties$Consumer`

| Key | Type | Description | Default value | Deprecation |
|-----|------|-------------|---------------|-------------|
|auto-offset-reset|java.lang.String||||

---

I'm expecting something like this:

---
### spring.kafka
**Class:** `org.springframework.boot.autoconfigure.kafka.KafkaProperties$Consumer`

| Key | Type | Description | Default value | Deprecation | Environment variable |
|-----|------|-------------|---------------|-------------|----------------------|
|auto-offset-reset|java.lang.String|||| SPRING_KAFKA_AUTO_OFFSET_RESET
---

**Describe alternatives you've considered**
I can also create a [custom template compiler](https://github.com/rodnansol/spring-configuration-property-documenter/blob/master/docs/template-customization.adoc#custom-template-compiler)

# Edited

A new configuration key is introduced to the Maven plugin that let's the developer to include the environment variables in the final document.

**Comment by nandorholozsnyak** [comment]
Closed with #43 

Waiting for release, 0.4.0.

**Comment by nandorholozsnyak** [comment]
Release 0.4.0 is out @Allsimon, thank you again. Let me know your feedback on the changes I made too, all templates are now supporting the environment variable form.
