### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by nandorholozsnyak** [rodnansol/spring-configuration-property-documenter#6]
**Is your feature request related to a problem? Please describe.**
The project started with a Maven plugin and nowadays it is just not feasible to have a plugin for one build management tool, and from experience I think Maven is the more used tool for Java based projects but Gradle is also keeping up and we see a lot of Spring Boot projects with Gradle nowadays so it is a must to create a Gradle plugin for the tool.

**Describe the solution you'd like**
A Gradle plugin that mitigate the same functionalities as the Maven plugin. Please read the Maven plugin documentation for the already existing features/commands/goals.

**Comment by tkhadir** [comment]
Hello @nandorholozsnyak i'm using gradle exclusively i can give a help if you want to add the plugin

**Comment by nandorholozsnyak** [comment]
Hello @tkhadir ,

Thank you for your interest, I'm still searching spare time for this implementation, so if you have knowledge with creating a Gradle plugin, I'm down for an implementation.

Some requirements:
- As the project is built around a maven project it would be nice to have the Gradle plugin as a Maven module too.
- Resources, documentations about the publishing, as the project utilizes the JReleaser, I hope we can publish the Gradle plugin to the plugin repository easily.
- The plugin should be fully equivalent to the Maven plugin, so the same functionalities are required, with the same approach, please check the maven plugin code and documentation if you need more information about that.

Quick question: Where did you find the project? 😁

**Comment by tkhadir** [comment]
Hello @nandorholozsnyak,

Thanks for the infos i will take a look, it's colleague who showed your project it's very awsome 😄

**Comment by nandorholozsnyak** [comment]
Hello @tkhadir 

That is nice, thank you! If you start the implementation make sure to check the new release, a few new options are available for the Maven plugin, of course for an initial prototype not all needed, just to make sure you know how much effort you are taking over :D

**Comment by tkhadir** [comment]
Hello @nandorholozsnyak, i have started working on, i forked the master branch that i think contains the latest modifications 😄

**Comment by tkhadir** [comment]
Hello @nandorholozsnyak i have added the plugin and now i need to test the functionnalities and compare with the maven plugin have you created a discord channel or something like that to exchange more easily during a contribution ?

**Comment by nandorholozsnyak** [comment]
There is @tkhadir https://discord.gg/wNMktG5g

**Comment by tkhadir** [comment]
Hello @nandorholozsnyak i have created a pull request for the work in progress can you create a branch with the number of the issue as a branch name then you can or other person continue on the work when i'm not available

**Comment by tkhadir** [comment]
to publish the plugin in your local machine run ./gradlew publishToMavenLocal

**Comment by nandorholozsnyak** [comment]
Hello @tkhadir , thank you for your input, I have made progress on the changes, I hope I can finish soon, and release it to the world. Thank you again!
