### ISSUE TITLE
Multiple use of nested configuration results in multiple properties

### ISSUE THREAD

**Issue by Riggs333** [rodnansol/spring-configuration-property-documenter#71]
Given this type with nested configuration:
```java
@ConfigurationProperties("my.app.parent.my-app-configuration")
public record MyApplicationConfiguration(
        String foo,
        MyNestedChildConfiguration abc,
        MyNestedChildConfiguration efg,
        MyNestedChildConfiguration xyz
) {
    record MyNestedChildConfiguration(String bar) {
    }
}
```

resulting in `spring-configuration-metadata.json`:

```json
{
  "groups": [
    {
      "name": "my.app.parent.my-app-configuration",
      "type": "com.playground.springplayground.MyApplicationConfiguration",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration"
    },
    {
      "name": "my.app.parent.my-app-configuration.abc",
      "type": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration",
      "sourceMethod": "abc()"
    },
    {
      "name": "my.app.parent.my-app-configuration.efg",
      "type": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration",
      "sourceMethod": "efg()"
    },
    {
      "name": "my.app.parent.my-app-configuration.xyz",
      "type": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration",
      "sourceMethod": "xyz()"
    }
  ],
  "properties": [
    {
      "name": "my.app.parent.my-app-configuration.abc.bar",
      "type": "java.lang.String",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration"
    },
    {
      "name": "my.app.parent.my-app-configuration.efg.bar",
      "type": "java.lang.String",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration"
    },
    {
      "name": "my.app.parent.my-app-configuration.foo",
      "type": "java.lang.String",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration"
    },
    {
      "name": "my.app.parent.my-app-configuration.xyz.bar",
      "type": "java.lang.String",
      "sourceType": "com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration"
    }
  ],
  "hints": []
}
```

results in the generated markdown having the `bar` property wrongly three times inside each nested child group:

---

...
### Unknown group
**Class:** `Unknown`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
### my.app.parent.my-app-configuration
**Class:** `com.playground.springplayground.MyApplicationConfiguration`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
| foo| java.lang.String| | | | 
### my.app.parent.my-app-configuration.abc
**Class:** `com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 
### my.app.parent.my-app-configuration.efg
**Class:** `com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 
### my.app.parent.my-app-configuration.xyz
**Class:** `com.playground.springplayground.MyApplicationConfiguration$MyNestedChildConfiguration`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 
| bar| java.lang.String| | | | 

---

## Used versions:
* Java 17
* Spring Boot 3.1.1
* spring-configuration-property-documenter-maven-plugin 0.6.0

pom.xml snippet for plugin usage:
```xml
...
            <plugin>
                <groupId>org.rodnansol</groupId>
                <artifactId>spring-configuration-property-documenter-maven-plugin</artifactId>
                <version>0.6.0</version>
                <executions>
                    <execution>
                        <id>generate-markdown</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>generate-property-document</goal>
                        </goals>
                        <configuration>
                            <type>MARKDOWN</type>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
...
```

**Comment by nandorholozsnyak** [comment]
The fix will arrive in the 0.6.1 version.

**Comment by nandorholozsnyak** [comment]
Release is running, if it succeeds you should see the 0.6.1 in the Maven Central soon. Until then if you have some time I'm curious about how you found the project and using it, can you drop an answer here? :)

Thanks in advance!
https://github.com/rodnansol/spring-configuration-property-documenter/discussions/74

**Comment by Riggs333** [comment]
Hey @nandorholozsnyak - awesome! 🥳 That was really fast! 👍🏻
Thank you very much! 🙇🏻 
I will answer the questions in the discussions.

**Comment by nandorholozsnyak** [comment]
I appreciate the feedback. I'm trying to fix the issues as soon as I can. :)
