### ISSUE TITLE
Replace special characters with a post processing step

### ISSUE THREAD

**Issue by katiaxyz** [rodnansol/spring-configuration-property-documenter#78]
**Describe the bug**
If any of the cells are containing a pipe (|) symbol, the tables would be rendered in a wrong way.

**Expected behavior**
Tables must be rendered correctly, when any of the cells are containing pipe symbols.

Example:
```java
@Data
@ConfigurationProperties(prefix = "test-config")
public class TestConfigurationProperties {

    /**
     * Regular expression
     */
    private String myRegex = "(1|2|3)\\.item";
}
```

Pipe symbol must be replaced/escaped with the following:
- Markdown: `&#124`
- AsciiDoc: `\|`

**Comment by katiaxyz** [comment]
I define this class annotated with @ConfigurationProperties:

@Component
```
@Data
@ConfigurationProperties(prefix = "test-config")
public class TestConfigurationProperties {

    /**
     * Regular expression
     */
    private String myRegex = "(1|2|3)\\.item";
}
```

**Comment by katiaxyz** [comment]
I get this result in spring-configuration-metadata.json file:

```
{
      "name": "test-config.my-regex",
      "type": "java.lang.String",
      "description": "Regular expression",
      "sourceType": "com.vodafone.dxl.myvdf.chatbot.configuration.TestConfigurationProperties",
      "defaultValue": "(1|2|3)\\.item"
    },
```

**Comment by katiaxyz** [comment]
My .adoc file is as below:

<img width="1063" alt="Screenshot 2023-07-11 at 12 08 14" src="https://github.com/rodnansol/spring-configuration-property-documenter/assets/137886114/1ce252b0-d241-456e-92b8-1c23d669d408">

**Comment by katiaxyz** [comment]
pom.xml configuration:
```
<plugin>
				<groupId>org.rodnansol</groupId>
				<artifactId>spring-configuration-property-documenter-maven-plugin</artifactId>
				<version>0.6.0</version>
				<executions>
					<execution>
						<id>generate-adoc</id>
						<phase>process-classes</phase>
						<goals>
							<goal>generate-property-document</goal>
						</goals>
						<configuration>
							<type>ADOC</type>
							<outputFile>path-to-adoc-file</outputFile>
							<failOnError>true</failOnError>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by nandorholozsnyak** [comment]
Thank you, it is clear now.

**Comment by nandorholozsnyak** [comment]
AsciiDoc tables are built with the "|" (pipe) symbol so this is what causes the problem, it must be escaped so the basic templates must be changed, in the upcoming days I'll be picking it up. Until then I can not really suggest anything, because it would break your regexp, so please be patient with the fix.

Until then, can I ask you to give me some feedback in this [discussion](https://github.com/rodnansol/spring-configuration-property-documenter/discussions/74)? :)

Thanks in advance.
