### ISSUE TITLE
'Unknown group' appears in the generated output

### ISSUE THREAD

**Issue by mydeveloperplanet** [rodnansol/spring-configuration-property-documenter#92]
**Describe the bug**
I have four configuration classes. Each are properly shown in the generated output. However, also an 'Unknown group' is added. I can only get rid of it, when I add includedGroups tag in the configuration of the plugin which includes the files I would like to have in the output.

```
### Unknown group
**Class:** `Unknown`

|Key|Type|Description|Default value|Deprecation|
|---|----|-----------|-------------|-----------|
```

**To Reproduce**
1. Create one basic Configuration class
2. Add the maven plugin to the pom:
```
                                       <execution>
						<id>generate-markdown</id>
						<phase>process-classes</phase>
						<goals>
							<goal>generate-property-document</goal>
						</goals>
						<configuration>
							<type>MARKDOWN</type>
<!--							<includedGroups>-->
<!--								<value>my.first.properties</value>-->
<!--							</includedGroups>-->
						</configuration>
					</execution>
```
3. build the project
4. In the output, the following warning is raised:
```
[WARNING] Property group with name:[Unknown group] is having no properties, please check if you provided the getter/setter methods. If your class is empty intentionally, please forget this warning here.
```
5. The generated markdown file contains the unknown group
6. When uncommenting the includedGroups, the 'unknown group' is gone, as expected

**Expected behavior**
Only the configuration files are added to the output and not an 'unknown group'

**Comment by mydeveloperplanet** [comment]
My apologies, I just saw that there is a configuration in the markdownCustomization section. No issue.

**Comment by nandorholozsnyak** [comment]
Hello @mydeveloperplanet 

Please try to use the `includeUnknownGroup` configuration with the `false` value to remove the unknown group from the final document.

Please check the docs here: https://rodnansol.github.io/spring-configuration-property-documenter/latest/template-customization.html#template-customizations

```xml
                                       <execution>
						<id>generate-markdown</id>
						<phase>process-classes</phase>
						<goals>
							<goal>generate-property-document</goal>
						</goals>
						<configuration>
							<type>MARKDOWN</type>
                                                       <includeUnknownGroup>false</includeUnknownGroup>
						</configuration>
					</execution>
```
