### ISSUE TITLE
@ConditionalOnProperty

### ISSUE THREAD

**Issue by Hans-MartinHannibalLauridsen** [rodnansol/spring-configuration-property-documenter#96]
Unfortunately due to the way spring boot is build you cannot use the `@ConfigurationProperties` to enable and disable services. Thus we get to fallback on the `@ConditionalOnProperty` annotation. 

Having an annotation processor generating documentation for these would be much beneficial. 

Another option would be to allowed for a plugin sort of structure, where this library could pickup on a custom annotation processor or other metadata files. 

Super awesome idea, and great work btw.

**Comment by nandorholozsnyak** [comment]
Hello @Hans-MartinHannibalLauridsen 
I'm happy to see new users of the tool.

Yes, ConditionalOnProperty is definitely a thing that developers want to document, and the `@Value` is also having the same "interest". 

I see a few solutions and limitations:

- The tool itself is not an annotation processor, which means it just uses the output of the Spring annotation processer. Currently there are no plans to extend the functionality, but if there is any use cases we might do it. It depends.
- In this case, where would you define the description of the property inside the annotation? In the JavaDoc on the class? It would make no sense.

Possible solutions:
- I know projects where people tend to write their own additional-spring-configuration-metadata.json where they document their own use cases like this. I would advise you to read about it here: https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#appendix.configuration-metadata.annotation-processor.adding-additional-metadata

If you create your own json file inside the mentioned folder the Spring annotation processor will merge them together and the final JSON will contain your content too. It is a bit of a manual work, but it works!

**Comment by nandorholozsnyak** [comment]
Hello @Hans-MartinHannibalLauridsen
Did you check my earlier message? Are you satisfied with it? Or do you have anything on your mind?

**Comment by Hans-MartinHannibalLauridsen** [comment]
Thanks I think that will work for me. 

I believe that the description for the property in the @ConditionalOnProperty would be fairly static - at least for my use case, "com.fun.service.enabled activates the bean/service <class name>" maybe taking the javadoc describing the service class as well for additional information. I think I might make it work with if I spice in my own annotation processor for the @ConditionalOnProperty only. Thanks for the replay!

**Comment by nandorholozsnyak** [comment]
May I close this ticket @Hans-MartinHannibalLauridsen ?

**Comment by Hans-MartinHannibalLauridsen** [comment]
Please do.
